version: "3.9"
services:
  ffrd-ui:
    container_name: FFRD_UI_DEV
    # build:
    #   context: .
    #   dockerfile: dev.Dockerfile
    image: node:18.1-alpine3.14
    ports:
      # host:container
      - 3000:3000
      # this one is for live reload - looks like a static port
      # - 35729:35729
      # default for vite/sveltekit
      - 24678:24678
    volumes:
      - .:/workspaces/ffrd-ui
    # env_file:
    #   - .devcontainer/devcontainer.ui.env
    environment:
      - SVELTE_APP_KEYCLOAK_HOST=http://host.docker.internal:8080/auth
      - SVELTE_APP_KEYCLOAK_REALM=ffrd
      - SVELTE_APP_KEYCLOAK_CLIENTID=ffrd-ui
      - SVELTE_APP_KEYCLOAK_CLIENTSECRET=
      - SVELTE_APP_KEYCLOAK_REDIRECT=http://host.docker.internal:3000/ffrd-ui/splash
      - SVELTE_APP_BASEPATH=ffrd-ui
    working_dir: /workspaces/ffrd-ui
    tty: true

  auth:
    image: jboss/keycloak:16.1.1
    container_name: KEYCLOAK_FFRD_DEV
    command: ["-Djboss.http.port=8080","-Dkeycloak.migration.strategy=IGNORE_EXISTING"]
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./kdata:/opt/jboss/keycloak/standalone/data
